### ISSUE TITLE
AssertionError when using Method.VITALLENS on video input

### ISSUE THREAD

**Issue by ensiyehk** [Rouast-Labs/vitallens-python#4]
Hi,

Thanks for sharing the codes and detailed instructions.

However, when I use Method.VITALLENS as per your instruction to load and test the video file you provided in [your GitHub repository](https://github.com/Rouast-Labs/vitallens-python.git), I keep getting the following error:

line 39, in _get_roi_from_det
    assert isinstance(det, (tuple, np.ndarray)) and len(det) == 4 and all(isinstance(i, (int, np.int64)) for i in det)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Although I input the video file as instructed below:

from vitallens import VitalLens, Method
vl = VitalLens(method=Method.VITALLENS, api_key="YOUR_API_KEY")
result = vl("video.mp4")
print(result)

Any help would be greatly appreciated.

**Comment by prouast** [comment]
Hi @ensiyehk, this may be due to a bug I fixed recently.

Can you try running `pip install --upgrade vitallens prpy` to update and let me know if this issue persists?

**Comment by ensiyehk** [comment]
The issue is sorted after updating vitallens prpy. Thanks for your help!
