### ISSUE TITLE
camera input

### ISSUE THREAD

**Issue by mahilaMoghadami** [Rouast-Labs/vitallens-python#9]
I've just come up with your research  This is a very well-done research with a strong scientific base. It opens many new opportunities for application in medicine.

but how can I use your API to use  webcam as input.

Is it possible for you to share the weight of your model? or your dataset?

I would appreciate your response

**Comment by prouast** [comment]
Hi @mahilaMoghadami - for now this repository does not contain code to use the API live with a webcam. However I am considering to add this in the future as another demo, so I will keep this issue open for now.

Regarding the model weights and dataset: I am not able to share those with you. If you have academic affiliation, you may be able to get access to other related datasets such as UBFC-rPPG or PURE.

**Comment by prouast** [comment]
Hi @mahilaMoghadami - A sample script that allows you to use `vitallens` with your webcam in real-time has been added in [VitalLens 0.4](https://github.com/Rouast-Labs/vitallens-python/releases/tag/v0.4)
